# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobilKansizlik' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobilKansizlik
  pod 'FSPagerView'
  pod 'SDWebImage', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'AKSideMenu'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'UICircularProgressRing'
  
end
